title:          Saadah Gaming
description:    "Stop bermain judi slot. Mainkan saja permainan slot demo gratis tanpa deposit atau memakai uang asli."
baseurl:        "/games/"
url:            "https://as-saadah.github.io/games/"
markdown: kramdown
future: true
encoding: UTF-8
include:
  - _pages
  - _posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /news/:title
  - scope:
      path: "_pages"
      type: "pages"

plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
whitelist:
  - jekyll-redirect-from  
