title:          Play For Fun
description:    "Stop bermain judi slot. Mainkan saja games slot demo gratis tanpa deposit disitus kami."
baseurl:        "/games/"
url:            "https://as-saadah.github.io/games/"
markdown: kramdown
future: true
encoding: UTF-8
permalink: pretty
timezone: Aisa/Jakarta
collections:
  pages:
    output: true
    permalink: /:title/
  id:
    output: true
    permalink: /id/
  en:
    output: true
    permalink: /en/
