title:          Demo Games
description:    "Mainkan games slot demo secara gratis tanpa deposit."
baseurl:        "/games/"
url:            "https://as-saadah.github.io/games/"
markdown: kramdown
permalink: pretty
collections:
  pages:
    output: true
    permalink: /:title/
