title:          Saadah Gaming
description:    "Stop bermain judi slot. Mainkan saja games slot demo gratis tanpa deposit disitus kami."
baseurl:        "/games/"
url:            "https://as-saadah.github.io/games/"
markdown: kramdown
future: true
encoding: UTF-8
paginate: 6
paginate_path: "news/page:num/"
include:
  - _pages
  - _posts
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /news/:title
  - scope:
      path: "_pages"
      type: "pages"
